import ReactQueryProvider from './ReactQueryProvider';
import { MovieModalProvider } from '@/feature/movies/MovieModalProvider';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="min-h-full flex flex-col">
        <ReactQueryProvider>
          <MovieModalProvider>{children}</MovieModalProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
